resolver: lts-8.11

packages:
- '.'
- location:
    git:    https://github.com/mgajda/haskell-conll.git
    commit: 2048f6065031bdb5c2d9dd41fbdab83ee7b33867

extra-deps:
- haskell-conll-0.1.0.0

flags: {}

extra-package-dbs: []
